---
title: "Practica_2"
author: "Aniol, Omar, Marcel"
date: "2026-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("rvest")
install.packages("httr")
install.packages("XML")
install.packages("dplyr")
library(httr)
library(XML)
library(rvest)
library(dplyr)
```

## Pregunta 1:

### 1.

```{r}
enlace  <- "https://www.mediawiki.org/wiki/MediaWiki"
res <- GET(enlace) 
html_content <- content(res, "text", encoding = "UTF-8")

```

### 2.

```{r echo=TRUE}
doc <- htmlParse(html_content, asText = TRUE)
titulos <- xpathSApply(doc, "//title", xmlValue, "title")
print(titulos)
```

### 3.

```{r echo=TRUE}
doc <- htmlParse(html_content, asText = TRUE)
enlaces <- xpathSApply(doc, "//a", xmlGetAttr, "href")
text_enlace <- xpathSApply(doc, "//a", xmlValue)
is.null(text_enlace)
print(text_enlace)
```

### 4.

Para poder generar correctamente la tabla se han eliminado algunas entradas las cuales el enlace era solo un "\#".

```{r}
df_enlaces <- data.frame(url = enlaces, texto = text_enlace, stringsAsFactors = FALSE )

df_enlaces <- df_enlaces[df_enlaces$url!="#",]

df_enlaces_dedup <- df_enlaces %>% count(url, texto)
View(df_enlaces_dedup)



```

```{r}

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
